# Generated by Django 3.1 on 2020-08-31 04:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_date', models.DateField(default=datetime.date.today)),
                ('billed_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('provider_name', models.CharField(max_length=30)),
                ('claim_type', models.CharField(choices=[('Medical', 'Medical'), ('Rx', 'Rx'), ('Dental', 'Dental')], max_length=20)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='members.members')),
            ],
        ),
    ]
