# Generated by Django 3.1 on 2020-08-31 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accumulator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind_deduct_limit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ind_deduct_used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ind_ofp_limit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ind_ofp_used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('family_deduct_limit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('family_deduct_used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('family_ofp_limit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('family_ofp_used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.members')),
            ],
        ),
    ]
