# Generated by Django 3.1 on 2020-08-31 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('accumulators', '0002_auto_20200831_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accumulator',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accumulator', to='members.members'),
        ),
    ]
